### ISSUE TITLE
Не работает бот

### ISSUE THREAD

**Issue by ahvahsky2008** [otter18/serverless-tg-bot#1]
`{"errorMessage": "'data'", "errorType": "KeyError", "stackTrace": ["  File \"/function/runtime/runtime.py\", line 193, in handle_event\n    result = h(r.event, r.context)\n", "  File \"/function/code/index.py\", line 8, in handler\n    message = telebot.types.Update.de_json(event['data'])\n"]}`

Выдаёт такую ошибку

**Comment by otter18** [comment]
fixed with 905e323244526fcac1acda3f1d5cb9041c36b6de
